version: "3.9"
services:

  proxy:
    image: nginx:1.19.5
    volumes:
      - ./applications/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - apiserver

  apiserver:
    image: chenjr0719/gogolook-apiserver
    build:
      dockerfile: applications/apiserver/dockerfile
      context: .
    environment:
      - DATABASE_URI=mysql+pymysql://gogolook:gogolook@db:3306/gogolook
      - LOG_LEVEL=info
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql/mysql-server:8.0.23
    environment:
      - MYSQL_USER=gogolook
      - MYSQL_PASSWORD=gogolook
      - MYSQL_DATABASE=gogolook
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 1s
      retries: 10
      start_period: 30s

volumes:
  db-data: null
